export const testerArray = [
  {
    "id": 1,
    "period": {
      "id": 11,
      "Name": "202011",
      "StartDate": "2020-10-31",
      "EndDate": "2020-11-29",
      "published_at": "2020-11-12T19:16:44.000Z",
      "created_at": "2020-11-12T16:16:42.000Z",
      "updated_at": "2020-11-12T16:16:44.000Z",
      "FormattedName": "Nov 20"
    },
    "collaborator": {
      "id": 5,
      "FileId": "5",
      "LastName": "Perini",
      "FirstName": "Federico",
      "Area": "OPERACIONES",
      "job_title": null,
      "published_at": "2020-11-12T19:44:39.000Z",
      "created_at": "2020-11-12T16:44:36.000Z",
      "updated_at": "2020-11-18T11:22:33.000Z",
      "StartDate": "2020-11-08",
      "EndDate": null,
      "HiringType": "STAFFING",
      "AllocationType": "FULLTIME",
      "Photo": null
    },
    "currency": {
      "id": 1,
      "Name": "ARS",
      "published_at": "2020-10-26T18:16:10.000Z",
      "created_at": "2020-10-26T15:16:09.000Z",
      "updated_at": "2020-10-26T15:16:11.000Z",
      "Description": "Pesos Argentinos"
    },
    "Description": "asdf",
    "ServiceCost": 180,
    "published_at": "2020-12-11T12:11:04.000Z",
    "created_at": "2020-11-12T17:19:55.000Z",
    "updated_at": "2020-12-12T13:46:43.000Z",
    "contract": {
      "id": 2,
      "client_account": 3,
      "start_period": 10,
      "end_period": 13,
      "account_executive": 1,
      "Status": null,
      "currency": 1,
      "Name": "Equipo Dedicado >> Nov 20 - Ene 21",
      "Description": "Desarrollar un sitio que provea información estratégica para la empresa MICROSOFT donde pueda gestionar costos y rentabilidad por cada proyecto, unidad de negocio, etc. \n\nLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\nLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\nLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
      "Technologies": "Se utilizará NodeJS para el back\nSe utilizará ReactJS para el front\nSe acelerará el proyecto utilizando Strapi + Metronic\nLa base de datos será en MySQL\nEl cron integrador será en .NET o NodeJS\n\nLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
      "SimilarProjects": "**Pudu versión anterior**\n\nLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
      "Deadlines": "En enero tiene que salir a producción la primer versión, donde se logre: \n- Obtener Dashboard de Operaciones\n- Cargar gastos asociados a los proyectos\n- Levante información del acuerdo comercial\n\nEn siguientes etapas se deberá poder:\n- Agregar reportes y kpis al Dashboard de Operaciones\n- Agregar Carga de Contratos Comerciales\n- Agregar integración con Administración",
      "BenefitsForTheClient": "Tener un nuevo tablero de control permitirá escalar la gestión de los proyectos que el cliente pretende obtener en 2021. \nRealizar un sistema único integrador de contratos y proyectos permite centralizar información satelital comenzando a pensar en governance de información.",
      "Assumptions": "Si no se llega al release1 con carga de datos comerciales, se podrá utilizar Strapi para poder realizar carga de datos hasta que esté construido el front completo.",
      "Integrations": "- JIRA para obtener horas cargadas y planificadas\n- API de cotizaciones externa\n- XUBIO para enviar/consultar facturación\n- GOIARH para poder integrar colaboradores",
      "StakeHolders": "- Ariel Cabrejos , Director interesado en obtener KPIs estratégicos de alto nivel.\n- Guillermo Oliveti, Director de Operaciones interesado en el control focalizado en los contratos.\n- Gonzalo / Giuliana, Director y asistente Comerciales interesados en lograr cargar en un sistema el kickoff para los proyectso vendidos.\n- Melina, Responsable del área de Administración, quien está interesada en obtener un único lugar donde posea gestión de costos e imputación de gastos.\n",
      "published_at": "2020-11-12T20:00:01.000Z",
      "created_at": "2020-11-12T16:58:29.000Z",
      "updated_at": "2020-12-11T16:29:37.000Z",
      "business_unit": 4,
      "service_type": 2,
      "contract_billing": null,
      "billing_currency": 1,
      "BillingTrigger": "Mes_Vencido",
      "BillingDueDays": 30,
      "BillingContact": "Melina Berlanga",
      "BillingInfo": null,
      "BillingComments": null,
      "contract_status": 2,
      "contract_actual_cost": 3,
      "leader": 3,
      "EstimatedServiceCost": 40000,
      "PlannedServiceCost": 20000,
      "ConsumedServiceCost": 22000,
      "BillingInstructions": []
    },
    "service_cost_type": {
      "id": 1,
      "Name": "PorStaff",
      "published_at": "2020-11-12T20:01:23.000Z",
      "created_at": "2020-11-12T17:01:21.000Z",
      "updated_at": "2020-11-25T10:01:15.000Z",
      "IsStaffing": true,
      "IsExpenses": false,
      "Sufix": "%"
    },
    "Status": "Consumed",
    "Count": 1,
    "Date": "2020-11-30",
    "jira_project": null
  },
  {
    "id": 2,
    "period": {
      "id": 2,
      "Name": "202002",
      "StartDate": "2020-01-31",
      "EndDate": "2020-02-28",
      "published_at": "2020-10-26T18:34:07.000Z",
      "created_at": "2020-10-26T15:34:05.000Z",
      "updated_at": "2020-11-12T16:11:23.000Z",
      "FormattedName": "Feb 20"
    },
    "collaborator": {
      "id": 5,
      "FileId": "5",
      "LastName": "Perini",
      "FirstName": "Federico",
      "Area": "OPERACIONES",
      "job_title": null,
      "published_at": "2020-11-12T19:44:39.000Z",
      "created_at": "2020-11-12T16:44:36.000Z",
      "updated_at": "2020-11-18T11:22:33.000Z",
      "StartDate": "2020-11-08",
      "EndDate": null,
      "HiringType": "STAFFING",
      "AllocationType": "FULLTIME",
      "Photo": null
    },
    "currency": {
      "id": 1,
      "Name": "ARS",
      "published_at": "2020-10-26T18:16:10.000Z",
      "created_at": "2020-10-26T15:16:09.000Z",
      "updated_at": "2020-10-26T15:16:11.000Z",
      "Description": "Pesos Argentinos"
    },
    "Description": "fasdfasdfdsf",
    "ServiceCost": 1000,
    "published_at": "2020-12-11T12:11:11.000Z",
    "created_at": "2020-11-25T09:36:35.000Z",
    "updated_at": "2020-12-12T23:11:18.000Z",
    "contract": {
      "id": 2,
      "client_account": 3,
      "start_period": 10,
      "end_period": 13,
      "account_executive": 1,
      "Status": null,
      "currency": 1,
      "Name": "Equipo Dedicado >> Nov 20 - Ene 21",
      "Description": "Desarrollar un sitio que provea información estratégica para la empresa MICROSOFT donde pueda gestionar costos y rentabilidad por cada proyecto, unidad de negocio, etc. \n\nLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\nLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\nLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
      "Technologies": "Se utilizará NodeJS para el back\nSe utilizará ReactJS para el front\nSe acelerará el proyecto utilizando Strapi + Metronic\nLa base de datos será en MySQL\nEl cron integrador será en .NET o NodeJS\n\nLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
      "SimilarProjects": "**Pudu versión anterior**\n\nLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
      "Deadlines": "En enero tiene que salir a producción la primer versión, donde se logre: \n- Obtener Dashboard de Operaciones\n- Cargar gastos asociados a los proyectos\n- Levante información del acuerdo comercial\n\nEn siguientes etapas se deberá poder:\n- Agregar reportes y kpis al Dashboard de Operaciones\n- Agregar Carga de Contratos Comerciales\n- Agregar integración con Administración",
      "BenefitsForTheClient": "Tener un nuevo tablero de control permitirá escalar la gestión de los proyectos que el cliente pretende obtener en 2021. \nRealizar un sistema único integrador de contratos y proyectos permite centralizar información satelital comenzando a pensar en governance de información.",
      "Assumptions": "Si no se llega al release1 con carga de datos comerciales, se podrá utilizar Strapi para poder realizar carga de datos hasta que esté construido el front completo.",
      "Integrations": "- JIRA para obtener horas cargadas y planificadas\n- API de cotizaciones externa\n- XUBIO para enviar/consultar facturación\n- GOIARH para poder integrar colaboradores",
      "StakeHolders": "- Ariel Cabrejos , Director interesado en obtener KPIs estratégicos de alto nivel.\n- Guillermo Oliveti, Director de Operaciones interesado en el control focalizado en los contratos.\n- Gonzalo / Giuliana, Director y asistente Comerciales interesados en lograr cargar en un sistema el kickoff para los proyectso vendidos.\n- Melina, Responsable del área de Administración, quien está interesada en obtener un único lugar donde posea gestión de costos e imputación de gastos.\n",
      "published_at": "2020-11-12T20:00:01.000Z",
      "created_at": "2020-11-12T16:58:29.000Z",
      "updated_at": "2020-12-11T16:29:37.000Z",
      "business_unit": 4,
      "service_type": 2,
      "contract_billing": null,
      "billing_currency": 1,
      "BillingTrigger": "Mes_Vencido",
      "BillingDueDays": 30,
      "BillingContact": "Melina Berlanga",
      "BillingInfo": null,
      "BillingComments": null,
      "contract_status": 2,
      "contract_actual_cost": 3,
      "leader": 3,
      "EstimatedServiceCost": 40000,
      "PlannedServiceCost": 20000,
      "ConsumedServiceCost": 22000,
      "BillingInstructions": []
    },
    "service_cost_type": {
      "id": 2,
      "Name": "PorHora",
      "published_at": "2020-11-12T20:01:39.000Z",
      "created_at": "2020-11-12T17:01:30.000Z",
      "updated_at": "2020-11-25T10:50:45.000Z",
      "IsStaffing": true,
      "IsExpenses": false,
      "Sufix": "hs"
    },
    "Status": "Consumed",
    "Count": 45,
    "Date": "2020-11-29",
    "jira_project": null
  },
  {
    "id": 3,
    "period": {
      "id": 1,
      "Name": "202001",
      "StartDate": "2019-12-31",
      "EndDate": "2020-01-30",
      "published_at": "2020-10-26T18:33:26.000Z",
      "created_at": "2020-10-26T15:33:24.000Z",
      "updated_at": "2020-11-12T16:11:13.000Z",
      "FormattedName": "Ene 20"
    },
    "collaborator": {
      "id": 2,
      "FileId": "2",
      "LastName": "Cabrejos",
      "FirstName": "Ariel",
      "Area": "DIRECCION",
      "job_title": 6,
      "published_at": "2020-11-12T19:35:10.000Z",
      "created_at": "2020-11-12T16:35:07.000Z",
      "updated_at": "2020-11-16T15:19:53.000Z",
      "StartDate": "2019-09-03",
      "EndDate": null,
      "HiringType": "STAFFING",
      "AllocationType": "FULLTIME",
      "Photo": null
    },
    "currency": {
      "id": 1,
      "Name": "ARS",
      "published_at": "2020-10-26T18:16:10.000Z",
      "created_at": "2020-10-26T15:16:09.000Z",
      "updated_at": "2020-10-26T15:16:11.000Z",
      "Description": "Pesos Argentinos"
    },
    "Description": "Asignación Staff",
    "ServiceCost": 500,
    "published_at": "2020-12-11T12:28:14.000Z",
    "created_at": "2020-12-11T09:28:12.000Z",
    "updated_at": "2020-12-12T13:46:56.000Z",
    "contract": {
      "id": 1,
      "client_account": 1,
      "start_period": 11,
      "end_period": 13,
      "account_executive": 1,
      "Status": "Aprobado",
      "currency": 1,
      "Name": "Contract",
      "Description": "Contract",
      "Technologies": "Contract",
      "SimilarProjects": "Contract",
      "Deadlines": "Contract",
      "BenefitsForTheClient": "Contract",
      "Assumptions": "Contract",
      "Integrations": "Contract",
      "StakeHolders": null,
      "published_at": "2020-12-11T16:17:22.000Z",
      "created_at": "2020-10-27T14:33:49.000Z",
      "updated_at": "2020-12-11T17:04:58.000Z",
      "business_unit": 11,
      "service_type": 5,
      "contract_billing": null,
      "billing_currency": 1,
      "BillingTrigger": "Mes_Vencido",
      "BillingDueDays": null,
      "BillingContact": null,
      "BillingInfo": null,
      "BillingComments": null,
      "contract_status": 1,
      "contract_actual_cost": 1,
      "leader": 3,
      "EstimatedServiceCost": 120000,
      "PlannedServiceCost": 10000,
      "ConsumedServiceCost": 80000,
      "BillingInstructions": []
    },
    "service_cost_type": {
      "id": 1,
      "Name": "PorStaff",
      "published_at": "2020-11-12T20:01:23.000Z",
      "created_at": "2020-11-12T17:01:21.000Z",
      "updated_at": "2020-11-25T10:01:15.000Z",
      "IsStaffing": true,
      "IsExpenses": false,
      "Sufix": "%"
    },
    "Status": "Consumed",
    "Count": 75,
    "Date": "2020-11-30",
    "jira_project": null
  },
  {
    "id": 4,
    "period": {
      "id": 12,
      "Name": "202012",
      "StartDate": "2020-11-30",
      "EndDate": "2020-12-30",
      "published_at": "2020-11-12T19:17:06.000Z",
      "created_at": "2020-11-12T16:17:04.000Z",
      "updated_at": "2020-11-12T16:17:06.000Z",
      "FormattedName": "Dic 20"
    },
    "collaborator": {
      "id": 5,
      "FileId": "5",
      "LastName": "Perini",
      "FirstName": "Federico",
      "Area": "OPERACIONES",
      "job_title": null,
      "published_at": "2020-11-12T19:44:39.000Z",
      "created_at": "2020-11-12T16:44:36.000Z",
      "updated_at": "2020-11-18T11:22:33.000Z",
      "StartDate": "2020-11-08",
      "EndDate": null,
      "HiringType": "STAFFING",
      "AllocationType": "FULLTIME",
      "Photo": null
    },
    "currency": {
      "id": 1,
      "Name": "ARS",
      "published_at": "2020-10-26T18:16:10.000Z",
      "created_at": "2020-10-26T15:16:09.000Z",
      "updated_at": "2020-10-26T15:16:11.000Z",
      "Description": "Pesos Argentinos"
    },
    "Description": "Asignación Staff",
    "ServiceCost": 300,
    "published_at": "2020-12-15T08:21:17.000Z",
    "created_at": "2020-12-15T08:21:14.000Z",
    "updated_at": "2020-12-15T08:21:17.000Z",
    "contract": {
      "id": 2,
      "client_account": 3,
      "start_period": 10,
      "end_period": 13,
      "account_executive": 1,
      "Status": null,
      "currency": 1,
      "Name": "Equipo Dedicado >> Nov 20 - Ene 21",
      "Description": "Desarrollar un sitio que provea información estratégica para la empresa MICROSOFT donde pueda gestionar costos y rentabilidad por cada proyecto, unidad de negocio, etc. \n\nLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\nLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\nLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
      "Technologies": "Se utilizará NodeJS para el back\nSe utilizará ReactJS para el front\nSe acelerará el proyecto utilizando Strapi + Metronic\nLa base de datos será en MySQL\nEl cron integrador será en .NET o NodeJS\n\nLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
      "SimilarProjects": "**Pudu versión anterior**\n\nLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
      "Deadlines": "En enero tiene que salir a producción la primer versión, donde se logre: \n- Obtener Dashboard de Operaciones\n- Cargar gastos asociados a los proyectos\n- Levante información del acuerdo comercial\n\nEn siguientes etapas se deberá poder:\n- Agregar reportes y kpis al Dashboard de Operaciones\n- Agregar Carga de Contratos Comerciales\n- Agregar integración con Administración",
      "BenefitsForTheClient": "Tener un nuevo tablero de control permitirá escalar la gestión de los proyectos que el cliente pretende obtener en 2021. \nRealizar un sistema único integrador de contratos y proyectos permite centralizar información satelital comenzando a pensar en governance de información.",
      "Assumptions": "Si no se llega al release1 con carga de datos comerciales, se podrá utilizar Strapi para poder realizar carga de datos hasta que esté construido el front completo.",
      "Integrations": "- JIRA para obtener horas cargadas y planificadas\n- API de cotizaciones externa\n- XUBIO para enviar/consultar facturación\n- GOIARH para poder integrar colaboradores",
      "StakeHolders": "- Ariel Cabrejos , Director interesado en obtener KPIs estratégicos de alto nivel.\n- Guillermo Oliveti, Director de Operaciones interesado en el control focalizado en los contratos.\n- Gonzalo / Giuliana, Director y asistente Comerciales interesados en lograr cargar en un sistema el kickoff para los proyectso vendidos.\n- Melina, Responsable del área de Administración, quien está interesada en obtener un único lugar donde posea gestión de costos e imputación de gastos.\n",
      "published_at": "2020-11-12T20:00:01.000Z",
      "created_at": "2020-11-12T16:58:29.000Z",
      "updated_at": "2020-12-11T16:29:37.000Z",
      "business_unit": 4,
      "service_type": 2,
      "contract_billing": null,
      "billing_currency": 1,
      "BillingTrigger": "Mes_Vencido",
      "BillingDueDays": 30,
      "BillingContact": "Melina Berlanga",
      "BillingInfo": null,
      "BillingComments": null,
      "contract_status": 2,
      "contract_actual_cost": 3,
      "leader": 3,
      "EstimatedServiceCost": 40000,
      "PlannedServiceCost": 20000,
      "ConsumedServiceCost": 22000,
      "BillingInstructions": []
    },
    "service_cost_type": {
      "id": 1,
      "Name": "PorStaff",
      "published_at": "2020-11-12T20:01:23.000Z",
      "created_at": "2020-11-12T17:01:21.000Z",
      "updated_at": "2020-11-25T10:01:15.000Z",
      "IsStaffing": true,
      "IsExpenses": false,
      "Sufix": "%"
    },
    "Status": "Planned",
    "Count": 100,
    "Date": "2020-11-30",
    "jira_project": null
  },
  {
    "id": 5,
    "period": {
      "id": 13,
      "Name": "202101",
      "StartDate": "2020-12-31",
      "EndDate": "2021-01-30",
      "published_at": "2020-11-12T19:17:45.000Z",
      "created_at": "2020-11-12T16:17:42.000Z",
      "updated_at": "2020-11-12T16:17:45.000Z",
      "FormattedName": "Ene 21"
    },
    "collaborator": {
      "id": 5,
      "FileId": "7",
      "LastName": "Stukalov",
      "FirstName": "Aleksei",
      "Area": "OPERACIONES",
      "job_title": null,
      "published_at": "2020-11-12T19:44:39.000Z",
      "created_at": "2020-11-12T16:44:36.000Z",
      "updated_at": "2020-11-18T11:22:33.000Z",
      "StartDate": "2020-11-08",
      "EndDate": null,
      "HiringType": "STAFFING",
      "AllocationType": "FULLTIME",
      "Photo": null
    },
    "currency": {
      "id": 1,
      "Name": "ARS",
      "published_at": "2020-10-26T18:16:10.000Z",
      "created_at": "2020-10-26T15:16:09.000Z",
      "updated_at": "2020-10-26T15:16:11.000Z",
      "Description": "Pesos Argentinos"
    },
    "Description": "Asignación Staff",
    "ServiceCost": 400,
    "published_at": "2020-12-15T08:22:20.000Z",
    "created_at": "2020-12-15T08:22:17.000Z",
    "updated_at": "2020-12-15T08:22:20.000Z",
    "contract": {
      "id": 2,
      "client_account": 3,
      "start_period": 10,
      "end_period": 13,
      "account_executive": 1,
      "Status": null,
      "currency": 1,
      "Name": "Equipo Dedicado >> Nov 20 - Ene 21",
      "Description": "Desarrollar un sitio que provea información estratégica para la empresa MICROSOFT donde pueda gestionar costos y rentabilidad por cada proyecto, unidad de negocio, etc. \n\nLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\nLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.\nLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
      "Technologies": "Se utilizará NodeJS para el back\nSe utilizará ReactJS para el front\nSe acelerará el proyecto utilizando Strapi + Metronic\nLa base de datos será en MySQL\nEl cron integrador será en .NET o NodeJS\n\nLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
      "SimilarProjects": "**Pudu versión anterior**\n\nLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
      "Deadlines": "En enero tiene que salir a producción la primer versión, donde se logre: \n- Obtener Dashboard de Operaciones\n- Cargar gastos asociados a los proyectos\n- Levante información del acuerdo comercial\n\nEn siguientes etapas se deberá poder:\n- Agregar reportes y kpis al Dashboard de Operaciones\n- Agregar Carga de Contratos Comerciales\n- Agregar integración con Administración",
      "BenefitsForTheClient": "Tener un nuevo tablero de control permitirá escalar la gestión de los proyectos que el cliente pretende obtener en 2021. \nRealizar un sistema único integrador de contratos y proyectos permite centralizar información satelital comenzando a pensar en governance de información.",
      "Assumptions": "Si no se llega al release1 con carga de datos comerciales, se podrá utilizar Strapi para poder realizar carga de datos hasta que esté construido el front completo.",
      "Integrations": "- JIRA para obtener horas cargadas y planificadas\n- API de cotizaciones externa\n- XUBIO para enviar/consultar facturación\n- GOIARH para poder integrar colaboradores",
      "StakeHolders": "- Ariel Cabrejos , Director interesado en obtener KPIs estratégicos de alto nivel.\n- Guillermo Oliveti, Director de Operaciones interesado en el control focalizado en los contratos.\n- Gonzalo / Giuliana, Director y asistente Comerciales interesados en lograr cargar en un sistema el kickoff para los proyectso vendidos.\n- Melina, Responsable del área de Administración, quien está interesada en obtener un único lugar donde posea gestión de costos e imputación de gastos.\n",
      "published_at": "2020-11-12T20:00:01.000Z",
      "created_at": "2020-11-12T16:58:29.000Z",
      "updated_at": "2020-12-11T16:29:37.000Z",
      "business_unit": 4,
      "service_type": 2,
      "contract_billing": null,
      "billing_currency": 1,
      "BillingTrigger": "Mes_Vencido",
      "BillingDueDays": 30,
      "BillingContact": "Melina Berlanga",
      "BillingInfo": null,
      "BillingComments": null,
      "contract_status": 2,
      "contract_actual_cost": 3,
      "leader": 3,
      "EstimatedServiceCost": 40000,
      "PlannedServiceCost": 20000,
      "ConsumedServiceCost": 22000,
      "BillingInstructions": []
    },
    "service_cost_type": {
      "id": 1,
      "Name": "PorStaff",
      "published_at": "2020-11-12T20:01:23.000Z",
      "created_at": "2020-11-12T17:01:21.000Z",
      "updated_at": "2020-11-25T10:01:15.000Z",
      "IsStaffing": true,
      "IsExpenses": false,
      "Sufix": "%"
    },
    "Status": "Consumed",
    "Count": 150,
    "Date": "2020-12-01",
    "jira_project": null
  }
]
